### ISSUE TITLE
validThisSessionOnly and validBetweenSessions?

### ISSUE THREAD

**Issue by philipbjorge** [byoutline/EventCallback#4]
Can you explain what these do and what the usecases are for the feature?

**Comment by Naitbit** [comment]
Sure.
validThisSessionOnly will not deliver event if callback returns when sessionId is different than when call started.
validBetweenSessions will deliver event ignoring sessionId.

For example lets say that you have application that fetches user data and displays it. Call can take very long, and in the meantime user presses switch user. Than call for for previous user data returns. You probably do not want to display this data. If your sessionId is for example some session key, or user id, user name than call with validThisSessionOnly can discard this event for you.

**Comment by philipbjorge** [comment]
@Naitbit Interesting -- It sounds like this isn't really intended to address the issues described in the following blog post? http://itbrokeand.ifixit.com/2013/11/12/android-api-calls.html

Specifically, if I register something as validThisSessionOnly it will not post the event to the bus at all, correct?

**Comment by Naitbit** [comment]
Well if you set mActivityid as sessionId you can use it to ensure that you deliver only to specific activity. You are correct about event not being posted at all if session id does not match.

For caching there are multiple other mechanisms (generic like https://github.com/byoutline/CachedField, Http specific like Okhttp cache, RxJava specif cache() etc..).
